Tickets/preops 5100
lsst/dp0-3_lsst_io pull request #59
Opened 2024-05-10 00:07 UTC by Madejski

This is a pull request for Yumi to review the revised DP0.3 Portal tutorial 4 (phase curves).  The tutorial reflects the new UI, but does not have any substantive changes.  Let me know once you reviewed it - but please don't merge yet.

2024-05-11 00:07 UTC, galaxyumi requested changes, later dismissed
I left the only comment about the screenshot in S2.4. Other than that, it looks good to me. Nice job!

2024-05-11 00:07 UTC, galaxyumi commented on _static/portal_tut04_step02c.png
I can't see the Y column and Error on Y-axis in the screenshot.

2024-05-11 00:17 UTC, Madejski commented on _static/portal_tut04_step02c.png
Thanks!  I will fix it.

2024-05-13 18:52 UTC, Madejski commented on _static/portal_tut04_step02c.png
I just fixed it, and also cleaned up labels on the two plots in that part.  Thanks!

2024-05-16 21:22 UTC, ChristinaAdair approved these changes

2024-05-16 21:22 UTC, merged